### ISSUE TITLE
Random word error, problema de regexp.

### ISSUE THREAD

**Issue by Jackferson** [account0123/RAE-API#13]
Buenas, haciendo una gran cantidad de peticiones para obtener una palabra aleatoria me he encontrado con el siguiente error:

```
 const h = body.match(/<header [^>]*>([^<]+)/)[1]
                                                                               ^

TypeError: Cannot read properties of null (reading '1')
    at IncomingMessage.<anonymous> (lorem\node_modules\rae-api\src\HttpInterface.js:56:51)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

```

Según una pequeña revisión, llegué a la conclusión de que el problema ocurre porque el **header** incluye una etiqueta de cursiva "< i >" para envolver la palabra a definir, la cual evita que la función **regExp** encuentre el texto correspondiente y por lo tanto el método **.match** retorna un valor **null.**

Personalmente estoy intentando cambiar la función regExp para que permita seleccionar en los casos en que se cumpla esta condición pero tengo nula experiencia utilizando estas expresiones, si logro solucionarlo publicaré el cambio que realicé.

En caso de que tenga relevancia, lo único que estoy haciendo es ejecutar múltiples veces la función **getRandomWord**. Algunas veces logra ejecutarse 200 veces sin encontrar una palabra que produzca el problema pero en la mayoría de veces ocurre antes de llegar a ese punto. Todo lo que estoy ejecutando es:

```
const words = [];

async function randomWord() {
  const random = await rae.getRandomWord();
  const rWord = random.getHeader();
  words.push(rWord);
}

async function iterate() {
  for (let i = 0; i < 200; i++) {
    if (i % 10 == 0) {
      console.log(i);
    }
    await randomWord();
  }
  console.log(words);
}

iterate();

```

Gracias de antemano.

**Comment by account0123** [comment]
Agradezco la intención de encontrar una palabra que coincida con el bug, para tu información los header con `<i>` corresponden a extranjerismos. En mi caso utilizo *espanglish*. 
Respecto al bug, será solucionado en la próxima actualización. Muchas gracias por tu aporte.
