### ISSUE TITLE
Error en búsqueda de palabras cuando hay dos o más voces con idéntica forma 

### ISSUE THREAD

**Issue by aurpiqrod** [account0123/RAE-API#14]
Estoy usando el example GetDefinition.js en la última versión en Node.js v18.15.0, al hacer una búsqueda con una palabra con varias formas (ajo, champán, ...) resulta en un error: 

```node_modules\rae-api\src\HttpInterface.js:60
                                        const h = body.match(/<header .+>([^<]+)(<\/i>)?<\/h/)[1]
                                                                                              ^

TypeError: Cannot read properties of null (reading '1')
    at IncomingMessage.<anonymous> (C:\Users\niwlf\OneDrive\Escritorio\Github\letras\node_modules\rae-api\src\HttpInterface.js:60:60)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)```

**Comment by javigaralva** [comment]
A mí no me ocurre con `ajo`, ni `champán` (versión `1.5.1`), pero con la palabra "**tello**" sí que me ocurre el error en ese mismo punto (tanto versión `1.5.1`, como `1.5.2`)

Para la versión `1.5.2`

En una de las posibles definiciones, la expresión regular (línea 60 de `HttpInterface.js`)
```js
body.match(/<header .+>([^<]+)(<\/i>)?<\/h/)[1]
```
no hace maching con esta definición porque tiene la etiquetas `<i></i>` dentro del `header`

```html
<header title="Definición de tell" class="f"><i>tell</i></header>
```
