### ISSUE TITLE
Typo in reject promise

### ISSUE THREAD

**Issue by bryanjhv** [account0123/RAE-API#4]
`reject(error)` should be `reject(err)` or it masks the real error!

https://github.com/account0123/RAE-API/blob/a9d31e9e643080948c84837df1e8beffbcc5b114/src/HttpInterface.js#L73-L76

**Comment by account0123** [comment]
Logging is the only important thing. Anyways, there's no callback on rejection then that issue is not relevant.

Whatever, the issue will be fixed in next commit. Thanks for reporting.
