### ISSUE TITLE
Random Word

### ISSUE THREAD

**Issue by 3Cejas** [account0123/RAE-API#6]
Hola, me encanta y me es super útil tu API.

¿Crees que podrías implementar una función que te de una palabra aleatoria o cómo crees que se podría hacer?

Un saludo.

**Comment by account0123** [comment]
no sé jaja

**Comment by DanLop618** [comment]
Implementé un método que permite obtener las palabras aleatoriamente, además de incluir sus ID y definiciones. Solo esperemos que el merge se haga pronto. Para más info mira el Pull Request #9

**Comment by danflopss** [comment]
> Hola, me encanta y me es super útil tu API.
> 
> ¿Crees que podrías implementar una función que te de una palabra aleatoria o cómo crees que se podría hacer?
> 
> Un saludo.

Implementé un nuevo método que permite obtener palabras aleatorias que incluyan sus ID y definiciones :D
Para más info mira el Pull Request #9

**Comment by account0123** [comment]
Gracias por colaborar. Cerrando issue.
